mnist: 
  mnist_dir: '/path/to/mnist/folder'

multicenter:
  ts_paths: 
    mimic: '/path/to/mimic/folder'
    eicu: '/path/to/mimic/folder'
    hirid: '/path/to/mimic/folder'
    aumc: '/path/to/mimic/folder'